import react from '@vitejs/plugin-react-swc';
import { resolve } from 'path';
import { defineConfig } from 'vite';

const isLibrary = process.env.VITE_LIB === 'true';

export default defineConfig({
  plugins: [react()],
  resolve: {
    alias: {
      '@': resolve(__dirname, './src'),
    },
  },
  build: {
    sourcemap: true,
    outDir: isLibrary ? 'dist' : 'dist-site',
    // Only empty the directory when building the site.
    // For the library, we want to keep the types generated by tsc.
    emptyOutDir: !isLibrary,
    lib: isLibrary
      ? {
          entry: resolve(__dirname, 'src/index.ts'),
          name: 'GvtechDesign',
          // Matches the names in package.json
          fileName: (format) => `index.${format === 'es' ? 'es' : 'cjs'}.js`,
          formats: ['es', 'cjs'],
        }
      : undefined,
    rollupOptions: {
      external: isLibrary ? ['react', 'react-dom', 'prop-types'] : [],
      output: {
        globals: isLibrary
          ? {
              react: 'React',
              'react-dom': 'ReactDOM',
              'prop-types': 'PropTypes',
            }
          : {},
        manualChunks(id) {
          if (id.includes('node_modules')) {
            if (id.includes('axe-core')) return 'axe';
            if (id.includes('react-docgen')) return 'docgen';
            return 'vendor';
          }
        },
      },
    },
  },
});
