import react from '@vitejs/plugin-react-swc';
import fs from 'fs';
import { resolve } from 'path';
import { defineConfig } from 'vite';

const isLibrary = process.env.VITE_LIB === 'true';

// Get all UI components for multi-entry build
const getEntries = () => {
  const entries: Record<string, string> = {
    index: resolve(__dirname, 'src/index.ts'),
  };

  if (isLibrary) {
    const uiPath = resolve(__dirname, 'src/components/ui');
    const files = fs.readdirSync(uiPath);
    files.forEach((file) => {
      if (file.endsWith('.tsx') && !file.includes('.test.') && !file.includes('.stories.')) {
        const name = file.replace('.tsx', '');
        entries[name] = resolve(uiPath, file);
      }
    });
  }
  return entries;
};

export default defineConfig({
  plugins: [react()],
  resolve: {
    alias: {
      '@': resolve(__dirname, './src'),
    },
  },
  build: {
    sourcemap: true,
    outDir: isLibrary ? 'dist' : 'dist-site',
    // Only empty the directory when building the site.
    // For the library, we want to keep the types generated by tsc.
    emptyOutDir: !isLibrary,
    lib: isLibrary
      ? {
          entry: getEntries(),
          name: 'GvtechDesign',
          fileName: (format, entryName) =>
            entryName === 'index'
              ? `index.${format === 'es' ? 'es' : 'cjs'}.js`
              : `${entryName}.${format === 'es' ? 'es' : 'cjs'}.js`,
          formats: ['es', 'cjs'],
        }
      : undefined,
    rollupOptions: {
      external: isLibrary ? ['react', 'react-dom', 'prop-types', 'next-themes'] : [],
      output: {
        globals: isLibrary
          ? {
              react: 'React',
              'react-dom': 'ReactDOM',
              'prop-types': 'PropTypes',
              'next-themes': 'NextThemes',
            }
          : {},
        manualChunks(id) {
          if (id.includes('node_modules')) {
            if (id.includes('axe-core')) return 'axe';
            if (id.includes('react-docgen')) return 'docgen';
            return 'vendor';
          }
        },
      },
    },
  },
});
