// Generated by scripts/sync-tokens.ts - Do not edit manually
import 'package:flutter/material.dart';

/// GV Tech Design System Color Tokens
abstract class GVColors {
  // Palette Tokens
  static const Color brandBlue = Color(0xFF4169E1);
  static const Color brandGreen = Color(0xFF177246);
  static const Color brandFloralWhite = Color(0xFFFFFAF0);
  static const Color neutralWhite = Color(0xFFFFFFFF);
  static const Color neutralBlack = Color(0xFF000000);
  static const Color neutralGray50 = Color(0xFFF5F5F5);
  static const Color neutralGray100 = Color(0xFFEBEBEB);
  static const Color neutralGray200 = Color(0xFFE3E3E3);
  static const Color neutralGray300 = Color(0xFFE0E0E0);
  static const Color neutralGray400 = Color(0xFFB3B3B3);
  static const Color neutralGray500 = Color(0xFF65758B);
  static const Color neutralGray600 = Color(0xFF0F1729);
  static const Color neutralGray700 = Color(0xFF2E2E2E);
  static const Color neutralGray800 = Color(0xFF262626);
  static const Color neutralGray900 = Color(0xFF242424);
  static const Color neutralGray950 = Color(0xFF1C1C1C);
  static const Color neutralGray975 = Color(0xFF171717);
  static const Color neutralGray990 = Color(0xFF0F0F0F);
  static const Color semanticSuccess = Color(0xFF86AB69);
  static const Color semanticSuccessDark = Color(0xFF93C770);
  static const Color semanticDestructive = Color(0xFFEF4444);
  static const Color semanticDestructiveDark = Color(0xFF7F1D1D);

  // Light Theme Semantic Colors
  static const Color lightBackground = Color(0xFFF5F5F5);
  static const Color lightForeground = Color(0xFF0F1729);
  static const Color lightCard = Color(0xFFFFFFFF);
  static const Color lightCardForeground = Color(0xFF0F1729);
  static const Color lightPopover = Color(0xFFFFFFFF);
  static const Color lightPopoverForeground = Color(0xFF0F1729);
  static const Color lightPrimary = Color(0xFF4169E1);
  static const Color lightPrimaryForeground = Color(0xFFFFFFFF);
  static const Color lightSecondary = Color(0xFF86AB69);
  static const Color lightSecondaryForeground = Color(0xFFFFFFFF);
  static const Color lightMuted = Color(0xFFEBEBEB);
  static const Color lightMutedForeground = Color(0xFF65758B);
  static const Color lightAccent = Color(0xFFE0E0E0);
  static const Color lightAccentForeground = Color(0xFF0F1729);
  static const Color lightDestructive = Color(0xFFEF4444);
  static const Color lightDestructiveForeground = Color(0xFFFFFFFF);
  static const Color lightBorder = Color(0xFFE3E3E3);
  static const Color lightInput = Color(0xFFE3E3E3);
  static const Color lightRing = Color(0xFF0F1729);
  static const Color lightSidebar = Color(0xFFF5F5F5);
  static const Color lightSidebarForeground = Color(0xFF0F1729);
  static const Color lightSidebarPrimary = Color(0xFF4169E1);
  static const Color lightSidebarPrimaryForeground = Color(0xFFFFFFFF);
  static const Color lightSidebarAccent = Color(0xFFEBEBEB);
  static const Color lightSidebarAccentForeground = Color(0xFF242424);
  static const Color lightSidebarBorder = Color(0xFFE3E3E3);
  static const Color lightSidebarRing = Color(0xFF4169E1);

  // Dark Theme Semantic Colors
  static const Color darkBackground = Color(0xFF171717);
  static const Color darkForeground = Color(0xFFFFFFFF);
  static const Color darkCard = Color(0xFF242424);
  static const Color darkCardForeground = Color(0xFFFFFFFF);
  static const Color darkPopover = Color(0xFF1C1C1C);
  static const Color darkPopoverForeground = Color(0xFFFFFFFF);
  static const Color darkPrimary = Color(0xFF6E8DFC);
  static const Color darkPrimaryForeground = Color(0xFF171717);
  static const Color darkSecondary = Color(0xFF93C770);
  static const Color darkSecondaryForeground = Color(0xFF171717);
  static const Color darkMuted = Color(0xFF0F0F0F);
  static const Color darkMutedForeground = Color(0xFFB3B3B3);
  static const Color darkAccent = Color(0xFF262626);
  static const Color darkAccentForeground = Color(0xFFFFFFFF);
  static const Color darkDestructive = Color(0xFF7F1D1D);
  static const Color darkDestructiveForeground = Color(0xFFFFFFFF);
  static const Color darkBorder = Color(0xFF2E2E2E);
  static const Color darkInput = Color(0xFF2E2E2E);
  static const Color darkRing = Color(0xFFE6E6E6);
  static const Color darkSidebar = Color(0xFF1C1C1C);
  static const Color darkSidebarForeground = Color(0xFFB3B3B3);
  static const Color darkSidebarPrimary = Color(0xFF6E8DFC);
  static const Color darkSidebarPrimaryForeground = Color(0xFFFFFFFF);
  static const Color darkSidebarAccent = Color(0xFF262626);
  static const Color darkSidebarAccentForeground = Color(0xFFFFFFFF);
  static const Color darkSidebarBorder = Color(0xFF2E2E2E);
  static const Color darkSidebarRing = Color(0xFF6E8DFC);
}

/// GV Tech Design System Spacing Tokens (in logical pixels)
abstract class GVSpacing {
  static const double s0 = 0.0;
  static const double s1 = 4.0;
  static const double s2 = 8.0;
  static const double s3 = 12.0;
  static const double s4 = 16.0;
  static const double s5 = 20.0;
  static const double s6 = 24.0;
  static const double s8 = 32.0;
  static const double s10 = 40.0;
  static const double s12 = 48.0;
  static const double s16 = 64.0;
  static const double s20 = 80.0;
  static const double s24 = 96.0;
  static const double s32 = 128.0;
}

/// GV Tech Design System Border Radius Tokens
abstract class GVRadii {
  static const double none = 0.0;
  static const double sm = 4.0;
  static const double md = 6.0;
  static const double lg = 8.0;
  static const double xl = 12.0;
  static const double x2l = 16.0;
  static const double full = 9999.0;
}

/// GV Tech Design System Flutter ThemeData Factory
abstract class GVThemeData {
  static ThemeData light() {
    return ThemeData(
      brightness: Brightness.light,
      scaffoldBackgroundColor: GVColors.lightBackground,
      colorScheme: const ColorScheme.light(
        primary: GVColors.lightPrimary,
        onPrimary: GVColors.lightPrimaryForeground,
        secondary: GVColors.lightSecondary,
        onSecondary: GVColors.lightSecondaryForeground,
        error: GVColors.lightDestructive,
        onError: GVColors.lightDestructiveForeground,
        surface: GVColors.lightCard,
        onSurface: GVColors.lightCardForeground,
      ),
    );
  }

  static ThemeData dark() {
    return ThemeData(
      brightness: Brightness.dark,
      scaffoldBackgroundColor: GVColors.darkBackground,
      colorScheme: const ColorScheme.dark(
        primary: GVColors.darkPrimary,
        onPrimary: GVColors.darkPrimaryForeground,
        secondary: GVColors.darkSecondary,
        onSecondary: GVColors.darkSecondaryForeground,
        error: GVColors.darkDestructive,
        onError: GVColors.darkDestructiveForeground,
        surface: GVColors.darkCard,
        onSurface: GVColors.darkCardForeground,
      ),
    );
  }
}
