import * as fs from 'node:fs';
import * as path from 'node:path';

// Generate contract verification files for Web and Native packages
// These files use pure TypeScript assignments to ensure that platform implementations
// strictly satisfy the ui-core base contracts.

const rootDir = process.cwd();
const coreIndexPath = path.join(rootDir, 'packages/ui-core/src/index.ts');
const webIndexPath = path.join(rootDir, 'packages/ui-web/src/index.ts');
const nativeIndexPath = path.join(rootDir, 'packages/ui-native/src/index.ts');

const webTestPath = path.join(rootDir, 'packages/ui-web/src/__contracts.ts');
const nativeTestPath = path.join(rootDir, 'packages/ui-native/src/__contracts.ts');

function extractExports(filePath: string): string[] {
  if (!fs.existsSync(filePath)) {
    return [];
  }
  const content = fs.readFileSync(filePath, 'utf-8');

  const exports = new Set<string>();
  const regex = /export\s+(?:type\s+)?{([^}]+)}/g;
  let match;
  while ((match = regex.exec(content)) !== null) {
    const exportedItems = match[1]
      .split(',')
      .map((s) => s.trim().split(/\s+as\s+/)[0])
      .filter(Boolean);
    exportedItems.forEach((item) => exports.add(item));
  }
  return Array.from(exports);
}

const coreExports = extractExports(coreIndexPath);
const webExports = extractExports(webIndexPath);
const nativeExports = extractExports(nativeIndexPath);

const basePropsList = coreExports.filter((e) => e.endsWith('BaseProps'));

function generateTestFile(platform: 'web' | 'native', platformExports: string[]) {
  const imports: string[] = [];
  const tests: string[] = [];

  basePropsList.forEach((basePropName) => {
    const componentName = basePropName.replace('BaseProps', '');

    if (platformExports.includes(componentName) && componentName !== 'FormControl') {
      imports.push(componentName);
      imports.push(basePropName);

      // Pure TS assignment check
      tests.push(
        `const _test_${componentName}: ${basePropName} = {} as React.ComponentProps<typeof ${componentName}>;`,
      );
    }
  });

  const content = `import * as React from 'react';

// These components and their base props are imported to verify that
// the platform-specific implementations correctly satisfy the ui-core contracts.
import {
  ${imports
    .filter((v, i, a) => a.indexOf(v) === i && !v.endsWith('BaseProps'))
    .sort()
    .join(',\n  ')}
} from './index';

import type {
  ${imports
    .filter((v, i, a) => a.indexOf(v) === i && v.endsWith('BaseProps'))
    .sort()
    .join(',\n  ')}
} from '@gv-tech/ui-core';

// This file is auto-generated by scripts/generate-contract-tests.ts
// Do not edit manually.
// It uses variable assignments to verify that implementations extend the base contracts.

${tests.join('\n')}

export {};
`;

  return content;
}

const webTestContent = generateTestFile('web', webExports);
fs.writeFileSync(webTestPath, webTestContent);
console.log(`✅ Generated ${path.relative(rootDir, webTestPath)}`);

const nativeTestContent = generateTestFile('native', nativeExports);
fs.writeFileSync(nativeTestPath, nativeTestContent);
console.log(`✅ Generated ${path.relative(rootDir, nativeTestPath)}`);

// Format the generated files
try {
  const { execSync } = require('node:child_process');
  execSync(`bunx prettier --write ${webTestPath} ${nativeTestPath}`, { stdio: 'ignore' });
  console.log('✅ Formatted contract test files.');
} catch (e) {
  // Ignore errors if prettier fails
}

// Cleanup old/conflicting files if they exist
const filesToDelete = [
  path.join(rootDir, 'packages/ui-web/src/__contracts.spec.ts'),
  path.join(rootDir, 'packages/ui-native/src/__contracts.spec.ts'),
  path.join(rootDir, 'packages/ui-web/src/__contracts.test-d.ts'),
  path.join(rootDir, 'packages/ui-native/src/__contracts.test-d.ts'),
];

filesToDelete.forEach((f) => {
  if (fs.existsSync(f)) {
    fs.unlinkSync(f);
  }
});
