import fs from 'fs';
import path from 'path';
// We use a dynamic import or relative require because we are running with tsx
// and want to avoid complex tsconfig path issues for a simple script.
import { palette } from '../packages/design-tokens/src/palette';
import { theme } from '../packages/design-tokens/src/theme';

const OUTPUT_CSS_PATH = path.join(process.cwd(), 'packages/design-tokens/src/theme.css');

/** Strips hsl() wrapper and commas to match Tailwind/shadcn expectation of "H S L" */
function formatTokenValue(value: string) {
  if (value.includes('hsl')) {
    return value.replace(/hsl\((.*)\)/, '$1').replace(/,/g, '');
  }
  return value;
}

/** Converts camelCase to kebab-case */
function toKebabCase(str: string) {
  return str.replace(/([A-Z])/g, '-$1').toLowerCase();
}

function generateCss() {
  let css = '/* Generated by scripts/sync-tokens.ts - Do not edit manually */\n';
  css += '@layer base {\n';
  css += '  :root {\n';

  // Light theme variables
  for (const [key, value] of Object.entries(theme.light)) {
    const cssVarName = `--${toKebabCase(key)}`;
    css += `    ${cssVarName}: ${formatTokenValue(value as string)};\n`;
  }

  css += '\n    /* Brand Tokens */\n';
  for (const [category, tokens] of Object.entries(palette)) {
    for (const [key, value] of Object.entries(tokens)) {
      const cssVarName = `--${toKebabCase(category)}-${toKebabCase(key)}`;
      css += `    ${cssVarName}: ${formatTokenValue(value as string)};\n`;
    }
  }

  css += '  }\n\n  .dark {\n';

  // Dark theme variables
  for (const [key, value] of Object.entries(theme.dark)) {
    const cssVarName = `--${toKebabCase(key)}`;
    css += `    ${cssVarName}: ${formatTokenValue(value as string)};\n`;
  }

  css += '  }\n}\n\n';

  // Tailwind v4 Theme mappings
  css += '/* Tailwind v4 color utilities - map CSS vars to theme */\n';
  css += '@theme {\n';

  // Base colors
  for (const key of Object.keys(theme.light)) {
    if (key === 'radius') {
      continue;
    } // Handled elsewhere or wait, radius is special
    const cssVarName = `--${toKebabCase(key)}`;
    css += `  --color-${toKebabCase(key)}: hsl(var(${cssVarName}));\n`;
  }

  css += '}\n';

  return css;
}

function syncTokens() {
  try {
    const cssContent = generateCss();
    fs.writeFileSync(OUTPUT_CSS_PATH, cssContent);
    console.log(`✅ Tokens synchronized successfully. Generated ${path.relative(process.cwd(), OUTPUT_CSS_PATH)}`);
  } catch (error) {
    console.error(`❌ Error generating tokens CSS:`, error);
  }
}

syncTokens();
