name: gv_ui_flutter
description: Flutter implementation of the GV Tech Design System components and design tokens.
version: 1.0.0
publish_to: "none"

environment:
  sdk: ">=3.4.0 <4.0.0"
  flutter: ">=3.19.0"

dependencies:
  flutter:
    sdk: flutter
  lucide_icons: ^0.257.0
  web: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
